import {
    ArrowUpRight,
    BriefcaseBusiness,
    Car,
    Coffee,
    Dumbbell,
    Gamepad2,
    Gift,
    GraduationCap,
    Heart,
    House,
    MoreHorizontal,
    Music,
    PawPrint,
    Pill,
    Plane,
    Shirt,
    ShoppingCart,
    Smartphone,
    Square,
    Utensils,
    Wifi,
    Zap,
} from 'lucide-vue-next';

export const categoryIcons = {
    heart: Heart,
    home: House,
    arrow: ArrowUpRight,
    food: Utensils,
    shopping: ShoppingCart,
    transport: Car,
    coffee: Coffee,
    work: BriefcaseBusiness,
    education: GraduationCap,
    travel: Plane,
    gift: Gift,
    phone: Smartphone,
    internet: Wifi,
    electricity: Zap,
    health: Pill,
    fitness: Dumbbell,
    music: Music,
    games: Gamepad2,
    pets: PawPrint,
    clothing: Shirt,
    square: Square,
    more: MoreHorizontal,
};

export const categoryColors = ['#2457DA', '#16815B', '#B34735', '#A8750D', '#7A52B9', '#637083'];
